import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  LuArrowRight,
  LuArchiveRestore,
  LuBot,
  LuBoxes,
  LuBrain,
  LuBriefcaseBusiness,
  LuBuilding2,
  LuCalendar,
  LuChartGantt,
  LuChartNoAxesCombined,
  LuCircleCheck,
  LuClock3,
  LuCloud,
  LuDatabase,
  LuDatabaseBackup,
  LuFileStack,
  LuFileText,
  LuFiles,
  LuFlag,
  LuGauge,
  LuGraduationCap,
  LuLandmark,
  LuLayers,
  LuLifeBuoy,
  LuLightbulb,
  LuListChecks,
  LuLockKeyhole,
  LuMessagesSquare,
  LuMonitor,
  LuNetwork,
  LuPanelsTopLeft,
  LuPresentation,
  LuRoute,
  LuScale,
  LuScanText,
  LuSearch,
  LuSettings,
  LuShieldCheck,
  LuSparkles,
  LuTable,
  LuTags,
  LuTarget,
  LuTriangleAlert,
  LuUserRound,
  LuUsers,
  LuWaypoints,
  LuWorkflow,
} from "react-icons/lu";

export const approvedReactIcons = Object.freeze({
  insight: LuLightbulb,
  target: LuTarget,
  growth: LuChartNoAxesCombined,
  people: LuUsers,
  shield: LuShieldCheck,
  clock: LuClock3,
  cloud: LuCloud,
  settings: LuSettings,
  data: LuDatabase,
  warning: LuTriangleAlert,
  check: LuCircleCheck,
  idea: LuLightbulb,
  search: LuSearch,
  compliance: LuScale,
  decision: LuTarget,
  lock: LuLockKeyhole,
  network: LuNetwork,
  document: LuFileText,
  communication: LuMessagesSquare,
  recovery: LuLifeBuoy,
  backup: LuArchiveRestore,
  legal: LuLandmark,
  monitor: LuMonitor,
  automation: LuBot,
  arrow: LuArrowRight,
  brain: LuBrain,
  workflow: LuWorkflow,
  layers: LuLayers,
  files: LuFiles,
  table: LuTable,
  calendar: LuCalendar,
  gantt: LuChartGantt,
  flag: LuFlag,
  person: LuUserRound,
  organization: LuBuilding2,
  sparkles: LuSparkles,
  gauge: LuGauge,
  route: LuRoute,
  presentation: LuPresentation,
  training: LuGraduationCap,
  business: LuBriefcaseBusiness,
  checklist: LuListChecks,
  scan: LuScanText,
  tags: LuTags,
  components: LuBoxes,
  panels: LuPanelsTopLeft,
  waypoints: LuWaypoints,
  filestack: LuFileStack,
  databasebackup: LuDatabaseBackup,
});

export function renderApprovedReactIcon(iconName, options = {}) {
  const normalized = String(iconName ?? "").trim().toLowerCase();
  const Icon = approvedReactIcons[normalized];
  if (!Icon) {
    throw new Error(`Unsupported react-icons identifier: ${normalized || "(empty)"}`);
  }

  return renderToStaticMarkup(createElement(Icon, {
    "aria-hidden": "true",
    color: options.color ?? "currentColor",
    size: options.size ?? 96,
    strokeWidth: options.strokeWidth ?? 1.8,
    style: {
      display: "block",
      height: "100%",
      width: "100%",
    },
  }));
}
